### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by evgeniyprowork** [evgeniyprowork/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by damienasero** [comment]
1936 – Age 6
I started selling Juicy Fruit chewing gum packs. When asked for 1 piece, i would not sell as i thought i may be left with 4 pieces i could not sell. I made 2 cents profit per pack.

I would also purchase Coca-Cola six packs for 25 cents from his grandfather’s grocery store – I and Son. I would sell each Coke for 5 cents. Profit of 5 cents per pack.

1941 – Age 11
At 11 years old, i buy my first stock – 6 shares of Cities Service (now known as CITGO – an Oil company) at $38 per share. I bought 3 for myself and 3 for my sister Doris.

That is all the money i had at that time. Practiced little to no diversification at a young age which i continued to do throughout my investment career. The stock price fell to $27 but soon went to $40. I sold the stock at $40, but, the stock shot up to $202 in the next few years.

I later cited this experience as an early lesson in patience in investing.

1943 – Age 13
I file my first tax return and deducts my bike as a work expense for $35.

1945 – Age 15
I make $175 a month selling Washington Post newspapers and saves $1200 to buy a 40 acre farmland in Omaha, Nebraska.

1947 – Age 17
Join my friend Donald Danly to start a company called Wilson Coin Operated Machines. The business buys a pinball machine at a cost of $25 and places it in a nearby barber shop. Wilson Coin makes $50 per week for Me and Donald.

I do tax returns for myself and Wilson Coin. In next few months they own 3 machines and a year later sells it for $1200.

1949 to 1954 – Age 19 to 24
I saving reaches $9800.

I join Columbia University and learns from Benjamin Graham. I were willing to work for Benjamin Graham, even for free, but was not offered a job.

I returned to Omaha, purchased a Texaco station, but did not go well. I were also working as an investment salesman for Buffett-Falk & Company, at his father’s brokerage firm.

In 1954, Benjamin Graham called me again and offered me a job for $12,000 a year. During this period, I were able to also work closely with Walter Schloss.

1956 – Age 26
Graham decides to retire and fold my business. My saving have grown from $9,800 to $140,000.

I returned to Omaha and on May 1, created Buffett Associates Ltd. Seven family members and friends invest a total of $105k. I invested only $100k.

1957 – Age 27
Created more partnerships and was managing a total of 5 partnerships, all from my home.

1958 – Age 28
After 3 years, I doubled the partner’s money.

1959 – Age 29
I were introduced to Charlie Munger by my friend Edwin Davis at a dinner. Charlie Munger later becomes the Vice Chairman of Berkshire Hathaway.

1961 – Age 31
I am running seven partnerships by 1961; Buffett Associates, Buffett Fund, Dacee, Emdee, Glenoff, Mo-Buff, and Underwood.

The partnerships are worth a few million and Buffett made my first million dollar investment in Dempster – a windmill manufacturing company.

Sanborn Map Company accounted for 35% of the partnerships’ assets. I explained to the partners that in 1958 Sanborn was selling at $45 per share when the value of its investment portfolio itself was at $65 per share which meant that it was undervalued by $20 per share with a map business coming in for nothing.

I reveal that i earned a spot on the board of Sanborn.

1962 – Age 32
I go to New York to meet my old acquaintances to include more partners and raise capital. I collect a few hundreds of thousand dollars. My partnerships is worth $7.2 million. I then merges all partnerships into one and rename it as Buffett Partnerships Ltd.

Munger introduces Buffett to Harry Bottle, CEO of Dempster,  who cut costs, laid off workers, and turned around Dempster to generate cash. At this time, i notice Berkshire Hathaway selling for $8 a share and starts buying aggressively.

1963 – Age 33
I sell Dempster for a $2.3 million gain, 3x times the invested amount.

I aggressively purchase Berkshire paying $14.86 per share while the company had working capital of $19 per share. This did not include the value of fixed assets. My partnership become a single largest shareholder of Berkshire Hathaway.

1964 – Age 34
American Express is victim to the salad oil scandal and shares fall to $35. I saw the value and bought 5% of the company.

1965 – Age 35
Invest $4 million in Walt Disney after a meeting with Walt Disney himself which is almost 5% of the company. I take full control of Berkshire Hathaway and names Ken Chase to be the CEO.

1966 – Age 36
I close the partnership to new money. I write in my letter that “unless it appears that circumstances have changed (under some conditions added capital would improve results) or unless new partners can bring some asset to the partnership other than simply capital, I intend to admit no additional partners to BPL.”

Invest in Hochschild, Kohn which was a department store in Baltimore.

My personal investment in the partnership is now approximately $6.8 million.

1967 – Age 37
My Partnership now owns 59.5% of Berkshire Hathaway. Berkshire Hathaway pays a 10 cent dividend. This is the first and only dividend it has paid ever.

The Partnership is worth $65 million. My personal investment is $10 million. Itell my partners that in the current raging bull market he is unable to find good investments.

I also briefly considered leaving investing to pursue other interests.

American Express hits $180, making a $20 million profit on $13 million investment.

Berkshire Hathaway acquires National Indemnity Insurance for $8.6 million.

Berkshire acquires National Fire and Marine Insurance Company.

1968 – Age 38
Partnership is worth $104 million.

1969 – Age 39
Berkshire acquires Sun Newspapers (Publishing), Rockford Bank (Banking), Illinois National Bank (Banking) and Blacker Printing Company (Publishing).

I decide to close the partnership and liquidate the assets to the partners.

From 1957-1969 My Partnership returns were 29.5%.

I have three recommendations to partners.

Consider joining Bill Ruane’s Sequoia Fund
Take the cash
Take shares in Berkshire Hathaway that i now controls
My personal stake is now worth $25 million.

1970 – Age 40
My Partnership is completely dissolved and divested of its assets.

1972 – Age 42
Through Blue Chips Stamp Company, Berkshire buys See’s Candies (Chocolates) and Wesco Financial Corp (Financial Services).

1973 – Age 43
Berkshire starts buying stocks in the Washington Post company (Publishing). I becomesclose friends with Katharine Graham who controlled the company and its flagship newspaper and becomes a member of the board of directors.

1974 – Age 44
Due to falling stock prices, the value of Berkshire Hathaway portfolio begins to fall. My personal network falls by more than 50%.

1975 – Age 45
Merge Berkshire and Diversified – the firm controlled by Munger.

Munger gets 2% stock of Berkshire and becomes its vice chairman.

1976 – Age 46
Berkshire invests $4 million in GEICO (Insurance) when its stock price was just above $2. Icontinually invests in GEICO until 1996, when Berkshire acquires the company.

Berkshire’s subsidiary, National Fire and Marine Insurance Company, acquires Central Fire & Casualty Company, and Cypress Insurance Company.

1977 – Age 47
Berkshire invests in the Buffalo Evening News (Publishing) for $32.5 million. I also invests in Interpublic (Advertising) and Ogilvy & Mather (Advertising), Kaiser Industries (Metals and Mining), and Knight-Rider (Publishing).

1978 – Age 48
Berkshire invests in SAFECO (Insurance), ABC Broadcasting (TV Network).

1979 – Age 49
Berkshire is trading at $290 per share.

My personal net worth is now approximately $100 million and receives a $50k annual salary.

Berkshire starts to buy shares in General Foods (Foods), Handy & Harman (Metals and Mining), Affiliated Publications (Publishing), Media General (Publishing), FW Woolworth (Retail), Amerada Hess (Oil), Precision Steel Warehouse (Materials and Construction).

1980 – Age 50
Berkshire buys stock in RJ Reynolds (Tobacco), ALCOA (Metals and Mining), Pinkerton (Professional Services), Cleveland-Cliffs Iron (Metals and Mining), National Detroit (Banking), Times Mirror (Publishing), National Student Marketing (Financial Services).

1981 – Age 51
Berkshire buys Arcata (Forest products/Paper), and GATX (machinery).

1982 – Age 52
Buffalo Evening News is the only local newspaper of Buffalo and its name is changed to Buffalo News.

The newspaper earns $19 million in its first year without competition. By the late eighties, the Buffalo News is earning $40 million a year.

Berkshire invests in Time (Publishing), Crum & Forster (Insurance).

1983 – Age 53
Berkshire merges with Blue Chip Stamps which was a majority owned subsidiary of Berkshire.

Berkshire Hathaway purchases Nebraska Furniture Mart (Furniture) for $60 million.

Berkshire portfolio is worth $1.3 billion.

Begins with a stock price of $775 and ends the year at $1310.

My personal net worth has ballooned to $620 million and he makes the Forbes millionaire list for the first time.

1984 – Age 54
Berkshire buys $139 million of Washington Public Power Supply System Bonds, invests in Exxon (Oil) and Northwest Industries (Diversified).

1985 – Age 55
I shut down Berkshire Hathaway’s textile business.

I help merge ABC TV Network and Capital Cities (Communications). I am forced to leave the board of Washington Post, as the legislation prohibited him from sitting on the boards of both Capital Cities and Washington Post.

Berkshire purchases Scott and Fetzer who boast products like Kirby vacuums and World Book Encyclopedia. Also buys Fecheimer Brothers (Uniform company) and Beatrice (Food).

1986 – Age 56
Berkshire acquires Fechheimer Brothers Company and invested in Lear Seagler (Aerospace)

Berkshire’s stock price soars above the $3,000 mark.

1987 – Age 57
The stock market crashes in October and Berkshire loses 25% of its value.

The stock prices goes from $4,200 to $3,100 and Buffett’s wealth falls by $320 million.

Berkshire buys 12% of Salomon Brothers (Investment Bank).

1988 – Age 58
I start buying Coca-Cola (Beverages) and eventually gains a 7% stake in the company for $1.2 billion.

Berkshire buys Freddie Mac (Financial Services).

1989 – Age 59
Berkshire acquires Borsheim’s (Jewelry) from the Friedman Family. Berkshire’s stock price rises from $4,800 to $8,000 per share.

Berkshire buys Gillette (Toiletries) and Buffett’s personal fortune rises to $3.8 billion.

1990 – Age 60
Berkshire buys 10% of Wells Fargo (Banking).

1991 – Age 61
Berkshire acquires H. H. Brown (Footwear) and starts buying M&T Bank (Banking).

I serve as the CEO of Solomon Brothers following the firm’s treasury bond trading scandal. Berkshire invests in Guinness (Beverages).

1992 – Age 62
Berkshire acquires Central States Indemnity Company (Insurance) of Omaha and Buffett continues to serve as interim Chairman at Solomon Brothers.

Berkshire becomes the largest shareholder of General Dynamics (Aerospace).

Berkshire’s stock shoots past the $10,000 mark.

1993 – Age 63
Berkshire acquires Dextor (Footwear) which turns out to be a bad investment.

1994 – Age 64
My Way by Robert G. Hagstrom Jr. is published and becomes a bestseller.

Berkshire invests in McDonald’s (Restaurants), Gannett (Publishing) and PNC Bank (Banking).

1995 – Age 65
Berkshire acquires Helzberg’s Diamond Shops (Jewelry) and R. C. Willey (Home Furnishings).

Berkshire Hathaway’s annual meeting is so well attended that it is held in Omaha’s Holiday Convention Center for the first time. Berkshire stock crosses $25,000 per share.

1996 – Age 66
Berkshire acquires the remaining stake in GEICO to become 100% owned subsidiary.

Berkshire acquires Flight Safety International (provider of professional aviation training).

Wesco Financial, a subsidiary of Berkshire, acquires Kansas Bankers Surety Co (Insurance).

1997 – Age 67
Berkshire acquires Star Furniture (Furniture) and International Dairy Queen (Fast Food restaurants), and also invests in Travelers (Insurance).

I invested 2% of his investment portfolio in silver.

I make a huge investment in US Airways (Airlines) which turns out to be a bad investment decision.

1998 – Age 68
Berkshire acquires General Re (Re-insurance) and Executive Jet, later renamed to NetJets (Private Aviation).

1999 – Age 69
Berkshire acquires Jordan’s Furniture Company, a Massachusetts based furniture powerhouse. Also buys parts of MidAmerican Energy Holdings Company, a utility company.

2000 – Age 70
I am still going strong.

Berkshire acquires a long list of companies.

Ben Bridge (Jewelry)
CORT, the leading national provider of rental furniture, accessories and related services in the growing “rent-to-rent” furniture rental industry.
Justin Industries including Acme Building Brands.
Shaw Industries, the world’s largest manufacturer of tufted broadloom carpets.
Benjamin Moore, a leading manufacturer and retailer of premium paints, stains and industrial coatings that was founded in 1883.
Buffett is named the top money manager of the 20th century in a survey by the Carson Group, ahead of Peter Lynch and John Templeton.

2001 – Age 71
The acquisitions and purchases continue to increase.

Berkshire acquires Johns Manville Corp (building products), MiTek, a provider of steel connector products, design engineering software and ancillary services for the global building components market.

Berkshire goes on to acquire XTRA Corporation (transport containers), H&R Block (Financial Services) and Moody’s Corporation (Financial Services).

Insurance claims from the 9/11 terrorist attack total $2.28 billion.

I apologize to my shareholders for failing to foresee the risk and properly price insurance coverage.

2002 – Age 72
Berkshire acquire Larson-Juhl, a custom picture frame maker, Fruit of the Loom (textile), Albecca (picture framing), Garan (apparel), CTB (farming equipment) and The Pampered Chef (kitchenware).

Berkshire and other investment groups buy $500 million in bonds issued by Level 3 Communications, the former Omaha fiber network company.

I enter a deal where $11 billion worth of forward contracts is delivered in US dollars against other currencies. By April 2006, his total gain on these contracts is over $2 billion.

2003 – Age 73
Berkshire acquires McLane (wholesale distributor), Clayton Homes (housing) and Burlington Industries, one of the world’s most diversified marketers and manufacturers of soft goods for apparel and interior furnishings.

2004 – Age 74
Bill Gates is elected as a director for Berkshire Hathaway.

2005 – Age 75
Berkshire acquires Medical Protective Company (Medical malpractice carrier) and Forest River (leisure vehicles).

Despite insurance business losses of about $2.5 billion caused by Hurricane Katrina, Berkshire records a gain of $5.6 billion.

Berkshire’s subsidiary, Shaw Industries, buys stock in Honeywell International. Berkshire joins the fun by buying Procter and Gamble (Consumer Goods) and Anheuser-Busch (Food and Beverage).

Berkshire stock crosses $90,000 per share.

2006 – Age 76
I announce in June that he will give away more than 80%, or about $37 billion, of my $44 billion fortune to five foundations in annual gifts of stock, starting July 2006. The largest contribution will go to the Bill and Melinda Gates Foundation.

Berkshire stock crosses $100,000 per share.

The list of acquisitions and stock purchases continue.

Business Wire (media distributor)
Russell Corporation (athletic apparel)
80% of the Iscar Metalworking Companies (IMC) in a transaction that valued IMC at US$5 billion.
Applied Underwriters (insurance)
TTI Inc (electronic components distributor)
Southern Energy Homes (utility)
Brooke Sports (athletic apparel)
2007 – Age 77
In a letter to shareholders, i announce that he is looking for a young successor or perhaps successors to run Berkshire.

I had previously selected Lou Simpson, who manages the investment via GEICO, to fill that role. However, Simpson is only six years younger than Buffett.

The companies bought that year include

Boat America Corporation, which owns Seaworthy Insurance Company and controls the Boat Owners Association of the United States.
Leading jewelry manufacturers Bel-Oro International and Aurafin LLC, which merges into Richline Group.
60% of Marmon Holdings (holding company that owns companies producing electrical components).
SE Homes (home construction)
BoatUS (Boat America Corporation is the main supplier of towing, insurance and other services to the nonprofit boater’s association)
2008 – Age 78
Berkshire buys out Marmon Holdings and Coachmen Industries becomes a part of Forest River (leisure vehicles).

Berkshire buys $4.4b in bonds from Mars Inc (food and beverage). Makes $680m in profit off the investment.

2009 – Age 79
Berkshire’s subsidiary, Shaw Industries, acquires Sportexe (a leading synthetic turf company).

Berkshire acquires Cavalier Homes (home building company).

A $5 billion “paper” loss on investments and derivatives triggers a first-quarter loss for Berkshire. It is the biggest loss since the 9/11 terrorist attack. But earnings rebound later in the year.

2010 – Age 80
Berkshire buys out railroad company Burlington Northern for $44 billion. As a result of the acquisition, Berkshire enters the S&P 500, replacing Burlington Northern Santa Fe.

Berkshire subsidiary, McLane Company, acquires Kahn Ventures.

Berkshire invests in Munich Re (Insurance).

2011 – Age 81
Berkshire acquires Lubrizol (Speciality Chemicals).

2012 – Age 82
Berkshire acquires Omaha World-Herald (Publishing) and invests in IBM (Technology).

2013 – Age 83
Berkshire acquires a 50% stake in H. J. Heinz Company (Food and Beverage).

2014 and Beyond
As Berkshire continues to accumulate more cash, it’s capital spending will increase and you will no doubt see big deals occur going forward.
I have one of the most illustrious investing careers the world has ever seen.

The story is not over yet.

**Comment by evgeniyprowork** [comment]
**Working experience:**

**1936 – Age 6**
I started selling Juicy Fruit chewing gum packs. When asked for 1 piece, i would not sell as i thought i may be left with 4 pieces i could not sell. I made 2 cents profit per pack.

I would also purchase Coca-Cola six packs for 25 cents from his grandfather’s grocery store – I and Son. I would sell each Coke for 5 cents. Profit of 5 cents per pack.

**1941 – Age 11**
At 11 years old, i buy my first stock – 6 shares of Cities Service (now known as CITGO – an Oil company) at $38 per share. I bought 3 for myself and 3 for my sister Doris.

That is all the money i had at that time. Practiced little to no diversification at a young age which i continued to do throughout my investment career. The stock price fell to $27 but soon went to $40. I sold the stock at $40, but, the stock shot up to $202 in the next few years.

I later cited this experience as an early lesson in patience in investing.

**1943 – Age 13**
I file my first tax return and deducts my bike as a work expense for $35.

**1945 – Age 15**
I make $175 a month selling Washington Post newspapers and saves $1200 to buy a 40 acre farmland in Omaha, Nebraska.

**1947 – Age 17**
Join my friend Donald Danly to start a company called Wilson Coin Operated Machines. The business buys a pinball machine at a cost of $25 and places it in a nearby barber shop. Wilson Coin makes $50 per week for Me and Donald.

I do tax returns for myself and Wilson Coin. In next few months they own 3 machines and a year later sells it for $1200.

**1949 to 1954 – Age 19 to 24**
I saving reaches $9800.

I join Columbia University and learns from Benjamin Graham. I were willing to work for Benjamin Graham, even for free, but was not offered a job.

I returned to Omaha, purchased a Texaco station, but did not go well. I were also working as an investment salesman for Buffett-Falk & Company, at his father’s brokerage firm.

In 1954, Benjamin Graham called me again and offered me a job for $12,000 a year. During this period, I were able to also work closely with Walter Schloss.

**1956 – Age 26**
Graham decides to retire and fold my business. My saving have grown from $9,800 to $140,000.

I returned to Omaha and on May 1, created Buffett Associates Ltd. Seven family members and friends invest a total of $105k. I invested only $100k.

**1957 – Age 27**
Created more partnerships and was managing a total of 5 partnerships, all from my home.

**1958 – Age 28**
After 3 years, I doubled the partner’s money.

**1959 – Age 29**
I were introduced to Charlie Munger by my friend Edwin Davis at a dinner. Charlie Munger later becomes the Vice Chairman of Berkshire Hathaway.

**1961 – Age 31**
I am running seven partnerships by 1961; Buffett Associates, Buffett Fund, Dacee, Emdee, Glenoff, Mo-Buff, and Underwood.

The partnerships are worth a few million and Buffett made my first million dollar investment in Dempster – a windmill manufacturing company.

Sanborn Map Company accounted for 35% of the partnerships’ assets. I explained to the partners that in 1958 Sanborn was selling at $45 per share when the value of its investment portfolio itself was at $65 per share which meant that it was undervalued by $20 per share with a map business coming in for nothing.

I reveal that i earned a spot on the board of Sanborn.

**1962 – Age 32**
I go to New York to meet my old acquaintances to include more partners and raise capital. I collect a few hundreds of thousand dollars. My partnerships is worth $7.2 million. I then merges all partnerships into one and rename it as Buffett Partnerships Ltd.

Munger introduces Buffett to Harry Bottle, CEO of Dempster, who cut costs, laid off workers, and turned around Dempster to generate cash. At this time, i notice Berkshire Hathaway selling for $8 a share and starts buying aggressively.

**1963 – Age 33**
I sell Dempster for a $2.3 million gain, 3x times the invested amount.

I aggressively purchase Berkshire paying $14.86 per share while the company had working capital of $19 per share. This did not include the value of fixed assets. My partnership become a single largest shareholder of Berkshire Hathaway.

**1964 – Age 34**
American Express is victim to the salad oil scandal and shares fall to $35. I saw the value and bought 5% of the company.

**1965 – Age 35**
Invest $4 million in Walt Disney after a meeting with Walt Disney himself which is almost 5% of the company. I take full control of Berkshire Hathaway and names Ken Chase to be the CEO.

**1966 – Age 36**
I close the partnership to new money. I write in my letter that “unless it appears that circumstances have changed (under some conditions added capital would improve results) or unless new partners can bring some asset to the partnership other than simply capital, I intend to admit no additional partners to BPL.”

Invest in Hochschild, Kohn which was a department store in Baltimore.

My personal investment in the partnership is now approximately $6.8 million.

**1967 – Age 37**
My Partnership now owns 59.5% of Berkshire Hathaway. Berkshire Hathaway pays a 10 cent dividend. This is the first and only dividend it has paid ever.

The Partnership is worth $65 million. My personal investment is $10 million. Itell my partners that in the current raging bull market he is unable to find good investments.

I also briefly considered leaving investing to pursue other interests.

American Express hits $180, making a $20 million profit on $13 million investment.

Berkshire Hathaway acquires National Indemnity Insurance for $8.6 million.

Berkshire acquires National Fire and Marine Insurance Company.

**1968 – Age 38**
Partnership is worth $104 million.

**1969 – Age 39**
Berkshire acquires Sun Newspapers (Publishing), Rockford Bank (Banking), Illinois National Bank (Banking) and Blacker Printing Company (Publishing).

I decide to close the partnership and liquidate the assets to the partners.

From 1957-1969 My Partnership returns were 29.5%.

I have three recommendations to partners.

Consider joining Bill Ruane’s Sequoia Fund
Take the cash
Take shares in Berkshire Hathaway that i now controls
My personal stake is now worth $25 million.

**1970 – Age 40**
My Partnership is completely dissolved and divested of its assets.

**1972 – Age 42**
Through Blue Chips Stamp Company, Berkshire buys See’s Candies (Chocolates) and Wesco Financial Corp (Financial Services).

**1973 – Age 43**
Berkshire starts buying stocks in the Washington Post company (Publishing). I becomesclose friends with Katharine Graham who controlled the company and its flagship newspaper and becomes a member of the board of directors.

**1974 – Age 44**
Due to falling stock prices, the value of Berkshire Hathaway portfolio begins to fall. My personal network falls by more than 50%.

**1975 – Age 45**
Merge Berkshire and Diversified – the firm controlled by Munger.

Munger gets 2% stock of Berkshire and becomes its vice chairman.

**1976 – Age 46**
Berkshire invests $4 million in GEICO (Insurance) when its stock price was just above $2. Icontinually invests in GEICO until 1996, when Berkshire acquires the company.

Berkshire’s subsidiary, National Fire and Marine Insurance Company, acquires Central Fire & Casualty Company, and Cypress Insurance Company.

**1977 – Age 47**
Berkshire invests in the Buffalo Evening News (Publishing) for $32.5 million. I also invests in Interpublic (Advertising) and Ogilvy & Mather (Advertising), Kaiser Industries (Metals and Mining), and Knight-Rider (Publishing).

**1978 – Age 48**
Berkshire invests in SAFECO (Insurance), ABC Broadcasting (TV Network).

**1979 – Age 49**
Berkshire is trading at $290 per share.

My personal net worth is now approximately $100 million and receives a $50k annual salary.

Berkshire starts to buy shares in General Foods (Foods), Handy & Harman (Metals and Mining), Affiliated Publications (Publishing), Media General (Publishing), FW Woolworth (Retail), Amerada Hess (Oil), Precision Steel Warehouse (Materials and Construction).

**1980 – Age 50**
Berkshire buys stock in RJ Reynolds (Tobacco), ALCOA (Metals and Mining), Pinkerton (Professional Services), Cleveland-Cliffs Iron (Metals and Mining), National Detroit (Banking), Times Mirror (Publishing), National Student Marketing (Financial Services).

**1981 – Age 51**
Berkshire buys Arcata (Forest products/Paper), and GATX (machinery).

**1982 – Age 52**
Buffalo Evening News is the only local newspaper of Buffalo and its name is changed to Buffalo News.

The newspaper earns $19 million in its first year without competition. By the late eighties, the Buffalo News is earning $40 million a year.

Berkshire invests in Time (Publishing), Crum & Forster (Insurance).

**1983 – Age 53**
Berkshire merges with Blue Chip Stamps which was a majority owned subsidiary of Berkshire.

Berkshire Hathaway purchases Nebraska Furniture Mart (Furniture) for $60 million.

Berkshire portfolio is worth $1.3 billion.

Begins with a stock price of $775 and ends the year at $1310.

My personal net worth has ballooned to $620 million and he makes the Forbes millionaire list for the first time.

**1984 – Age 54**
Berkshire buys $139 million of Washington Public Power Supply System Bonds, invests in Exxon (Oil) and Northwest Industries (Diversified).

**1985 – Age 55**
I shut down Berkshire Hathaway’s textile business.

I help merge ABC TV Network and Capital Cities (Communications). I am forced to leave the board of Washington Post, as the legislation prohibited him from sitting on the boards of both Capital Cities and Washington Post.

Berkshire purchases Scott and Fetzer who boast products like Kirby vacuums and World Book Encyclopedia. Also buys Fecheimer Brothers (Uniform company) and Beatrice (Food).

**1986 – Age 56**
Berkshire acquires Fechheimer Brothers Company and invested in Lear Seagler (Aerospace)

Berkshire’s stock price soars above the $3,000 mark.

**1987 – Age 57**
The stock market crashes in October and Berkshire loses 25% of its value.

The stock prices goes from $4,200 to $3,100 and Buffett’s wealth falls by $320 million.

Berkshire buys 12% of Salomon Brothers (Investment Bank).

**1988 – Age 58**
I start buying Coca-Cola (Beverages) and eventually gains a 7% stake in the company for $1.2 billion.

Berkshire buys Freddie Mac (Financial Services).

**1989 – Age 59**
Berkshire acquires Borsheim’s (Jewelry) from the Friedman Family. Berkshire’s stock price rises from $4,800 to $8,000 per share.

Berkshire buys Gillette (Toiletries) and Buffett’s personal fortune rises to $3.8 billion.

**1990 – Age 60**
Berkshire buys 10% of Wells Fargo (Banking).

**1991 – Age 61**
Berkshire acquires H. H. Brown (Footwear) and starts buying M&T Bank (Banking).

I serve as the CEO of Solomon Brothers following the firm’s treasury bond trading scandal. Berkshire invests in Guinness (Beverages).

**1992 – Age 62**
Berkshire acquires Central States Indemnity Company (Insurance) of Omaha and Buffett continues to serve as interim Chairman at Solomon Brothers.

Berkshire becomes the largest shareholder of General Dynamics (Aerospace).

Berkshire’s stock shoots past the $10,000 mark.

**1993 – Age 63**
Berkshire acquires Dextor (Footwear) which turns out to be a bad investment.

**1994 – Age 64**
My Way by Robert G. Hagstrom Jr. is published and becomes a bestseller.

Berkshire invests in McDonald’s (Restaurants), Gannett (Publishing) and PNC Bank (Banking).

**1995 – Age 65**
Berkshire acquires Helzberg’s Diamond Shops (Jewelry) and R. C. Willey (Home Furnishings).

Berkshire Hathaway’s annual meeting is so well attended that it is held in Omaha’s Holiday Convention Center for the first time. Berkshire stock crosses $25,000 per share.

**1996 – Age 66**
Berkshire acquires the remaining stake in GEICO to become 100% owned subsidiary.

Berkshire acquires Flight Safety International (provider of professional aviation training).

Wesco Financial, a subsidiary of Berkshire, acquires Kansas Bankers Surety Co (Insurance).

**1997 – Age 67**
Berkshire acquires Star Furniture (Furniture) and International Dairy Queen (Fast Food restaurants), and also invests in Travelers (Insurance).

I invested 2% of his investment portfolio in silver.

I make a huge investment in US Airways (Airlines) which turns out to be a bad investment decision.

**1998 – Age 68**
Berkshire acquires General Re (Re-insurance) and Executive Jet, later renamed to NetJets (Private Aviation).

**1999 – Age 69**
Berkshire acquires Jordan’s Furniture Company, a Massachusetts based furniture powerhouse. Also buys parts of MidAmerican Energy Holdings Company, a utility company.

**2000 – Age 70**
I am still going strong.

Berkshire acquires a long list of companies.

Ben Bridge (Jewelry)
CORT, the leading national provider of rental furniture, accessories and related services in the growing “rent-to-rent” furniture rental industry.
Justin Industries including Acme Building Brands.
Shaw Industries, the world’s largest manufacturer of tufted broadloom carpets.
Benjamin Moore, a leading manufacturer and retailer of premium paints, stains and industrial coatings that was founded in 1883.
Buffett is named the top money manager of the 20th century in a survey by the Carson Group, ahead of Peter Lynch and John Templeton.

**2001 – Age 71**
The acquisitions and purchases continue to increase.

Berkshire acquires Johns Manville Corp (building products), MiTek, a provider of steel connector products, design engineering software and ancillary services for the global building components market.

Berkshire goes on to acquire XTRA Corporation (transport containers), H&R Block (Financial Services) and Moody’s Corporation (Financial Services).

Insurance claims from the 9/11 terrorist attack total $2.28 billion.

I apologize to my shareholders for failing to foresee the risk and properly price insurance coverage.

**2002 – Age 72**
Berkshire acquire Larson-Juhl, a custom picture frame maker, Fruit of the Loom (textile), Albecca (picture framing), Garan (apparel), CTB (farming equipment) and The Pampered Chef (kitchenware).

Berkshire and other investment groups buy $500 million in bonds issued by Level 3 Communications, the former Omaha fiber network company.

I enter a deal where $11 billion worth of forward contracts is delivered in US dollars against other currencies. By April 2006, his total gain on these contracts is over $2 billion.

**2003 – Age 73**
Berkshire acquires McLane (wholesale distributor), Clayton Homes (housing) and Burlington Industries, one of the world’s most diversified marketers and manufacturers of soft goods for apparel and interior furnishings.

**2004 – Age 74**
Bill Gates is elected as a director for Berkshire Hathaway.

**2005 – Age 75**
Berkshire acquires Medical Protective Company (Medical malpractice carrier) and Forest River (leisure vehicles).

Despite insurance business losses of about $2.5 billion caused by Hurricane Katrina, Berkshire records a gain of $5.6 billion.

Berkshire’s subsidiary, Shaw Industries, buys stock in Honeywell International. Berkshire joins the fun by buying Procter and Gamble (Consumer Goods) and Anheuser-Busch (Food and Beverage).

Berkshire stock crosses $90,000 per share.

**2006 – Age 76**
I announce in June that he will give away more than 80%, or about $37 billion, of my $44 billion fortune to five foundations in annual gifts of stock, starting July 2006. The largest contribution will go to the Bill and Melinda Gates Foundation.

Berkshire stock crosses $100,000 per share.

The list of acquisitions and stock purchases continue.

Business Wire (media distributor)
Russell Corporation (athletic apparel)
80% of the Iscar Metalworking Companies (IMC) in a transaction that valued IMC at US$5 billion.
Applied Underwriters (insurance)
TTI Inc (electronic components distributor)
Southern Energy Homes (utility)
Brooke Sports (athletic apparel)

**2007 – Age 77**
In a letter to shareholders, i announce that he is looking for a young successor or perhaps successors to run Berkshire.

I had previously selected Lou Simpson, who manages the investment via GEICO, to fill that role. However, Simpson is only six years younger than Buffett.

The companies bought that year include

Boat America Corporation, which owns Seaworthy Insurance Company and controls the Boat Owners Association of the United States.
Leading jewelry manufacturers Bel-Oro International and Aurafin LLC, which merges into Richline Group.
60% of Marmon Holdings (holding company that owns companies producing electrical components).
SE Homes (home construction)
BoatUS (Boat America Corporation is the main supplier of towing, insurance and other services to the nonprofit boater’s association)

**2008 – Age 78**
Berkshire buys out Marmon Holdings and Coachmen Industries becomes a part of Forest River (leisure vehicles).

Berkshire buys $4.4b in bonds from Mars Inc (food and beverage). Makes $680m in profit off the investment.

**2009 – Age 79**
Berkshire’s subsidiary, Shaw Industries, acquires Sportexe (a leading synthetic turf company).

Berkshire acquires Cavalier Homes (home building company).

A $5 billion “paper” loss on investments and derivatives triggers a first-quarter loss for Berkshire. It is the biggest loss since the 9/11 terrorist attack. But earnings rebound later in the year.

**2010 – Age 80**
Berkshire buys out railroad company Burlington Northern for $44 billion. As a result of the acquisition, Berkshire enters the S&P 500, replacing Burlington Northern Santa Fe.

Berkshire subsidiary, McLane Company, acquires Kahn Ventures.

Berkshire invests in Munich Re (Insurance).

**2011 – Age 81**
Berkshire acquires Lubrizol (Speciality Chemicals).

**2012 – Age 82**
Berkshire acquires Omaha World-Herald (Publishing) and invests in IBM (Technology).

**2013 – Age 83**
Berkshire acquires a 50% stake in H. J. Heinz Company (Food and Beverage).

**2014 and Beyond**
As Berkshire continues to accumulate more cash, it’s capital spending will increase and you will no doubt see big deals occur going forward.
I have one of the most illustrious investing careers the world has ever seen.

The story is not over yet.
